// ===========================================================================
// SIMPLEIN Solutions — FAQ Database (200+ questions)
// ===========================================================================
// Searchable by the FAQ engine. Each entry has tags for weighted matching.
// ===========================================================================

export interface FaqEntry {
  id: string;
  category: string;
  question: string;
  answer: string;
  tags: string[];
}

export const faqDatabase: FaqEntry[] = [
  // ─── PRICING ───
  { id: "p1", category: "Pricing", question: "How much does a website cost?", answer: "Website costs depend on the type, complexity, and features required. A simple business website starts at a different range than a complex web application. We provide a detailed proposal after understanding your specific needs — the consultation is free.", tags: ["price", "cost", "website", "web", "budget"] },
  { id: "p2", category: "Pricing", question: "How much does a mobile app cost?", answer: "Mobile app pricing depends on the platform (iOS, Android, or both), features, backend requirements, and design complexity. We provide a tailored estimate after a free requirements discussion.", tags: ["price", "cost", "mobile", "app", "budget"] },
  { id: "p3", category: "Pricing", question: "Do you offer fixed-price projects?", answer: "Yes, we offer both fixed-price and time-and-material engagement models. Fixed-price works well when the scope is clearly defined upfront.", tags: ["price", "fixed", "project", "engagement"] },
  { id: "p4", category: "Pricing", question: "Do you offer payment plans?", answer: "Yes, we typically structure payments in milestones — for example, 30% upfront, 40% at mid-project, and 30% at delivery. We're flexible and can discuss a schedule that works for you.", tags: ["payment", "plan", "installment", "milestone"] },
  { id: "p5", category: "Pricing", question: "Is the consultation free?", answer: "Yes, the initial consultation is completely free with no obligation. It's a conversation to understand your needs and see if we're a good fit.", tags: ["consultation", "free", "cost", "meeting"] },
  { id: "p6", category: "Pricing", question: "Do you charge for project estimates?", answer: "No. We provide detailed project proposals and estimates at no cost. You only pay once you approve and we begin work.", tags: ["estimate", "proposal", "charge", "free"] },
  { id: "p7", category: "Pricing", question: "What is your hourly rate?", answer: "Our rates vary by service and complexity. Rather than quoting an hourly rate, we prefer to scope the project and provide a transparent fixed estimate. This protects both sides.", tags: ["hourly", "rate", "charge", "price"] },
  { id: "p8", category: "Pricing", question: "Can you work within a limited budget?", answer: "Absolutely. We work with businesses of all sizes. We'll help you prioritise features and find the most cost-effective approach for your budget.", tags: ["budget", "limited", "affordable", "cheap", "small"] },
  { id: "p9", category: "Pricing", question: "Do you offer discounts for startups?", answer: "We offer flexible pricing for startups and early-stage companies. We understand the constraints and can help you build an MVP within your budget.", tags: ["discount", "startup", "affordable", "mvp"] },
  { id: "p10", category: "Pricing", question: "How does hardware pricing work?", answer: "Hardware pricing depends on the specific models, quantities, and any additional services like installation or configuration. We source from authorised channels and provide competitive enterprise pricing.", tags: ["hardware", "price", "equipment", "cost"] },

  // ─── TIMELINE ───
  { id: "t1", category: "Timeline", question: "How long does it take to build a website?", answer: "A simple business website typically takes 2–4 weeks. A complex web application can take 2–4 months. Enterprise platforms may take 3–6 months. We'll give you a specific timeline during the proposal phase.", tags: ["timeline", "website", "duration", "weeks", "months"] },
  { id: "t2", category: "Timeline", question: "How long does mobile app development take?", answer: "Simple apps take 4–6 weeks, medium-complexity apps 2–3 months, and feature-rich platforms 4–6 months. Cross-platform (Flutter) helps reduce this significantly.", tags: ["timeline", "mobile", "app", "duration"] },
  { id: "t3", category: "Timeline", question: "Can you deliver a project urgently?", answer: "Yes, we can accommodate urgent timelines with a dedicated team and accelerated sprint cycles. We'll discuss feasibility during the scoping phase.", tags: ["urgent", "fast", "rush", "quick", "asap"] },
  { id: "t4", category: "Timeline", question: "How long does an ERP implementation take?", answer: "ERP implementations typically take 4–8 months depending on the number of modules, complexity, and data migration requirements.", tags: ["erp", "timeline", "enterprise", "implementation"] },
  { id: "t5", category: "Timeline", question: "How quickly can you deploy hardware?", answer: "Standard hardware deployment takes 1–2 weeks from order confirmation, including configuration and installation. Urgent requests can be expedited.", tags: ["hardware", "deploy", "delivery", "timeline"] },
  { id: "t6", category: "Timeline", question: "What is your typical project workflow?", answer: "We follow: Discovery → Planning → Design → Development → Testing → Deployment → Support. Each phase includes client checkpoints so there are no surprises.", tags: ["workflow", "process", "methodology", "phases"] },

  // ─── SUPPORT & MAINTENANCE ───
  { id: "s1", category: "Support", question: "Do you offer post-launch support?", answer: "Yes. Every project includes a post-launch support period (typically 30 days). After that, we offer ongoing maintenance plans and AMC contracts.", tags: ["support", "post-launch", "after", "delivery"] },
  { id: "s2", category: "Support", question: "What is an AMC?", answer: "AMC stands for Annual Maintenance Contract. It covers ongoing support, bug fixes, security updates, minor enhancements, and priority response times for a fixed annual fee.", tags: ["amc", "maintenance", "contract", "annual"] },
  { id: "s3", category: "Support", question: "Do you fix bugs after delivery?", answer: "Yes. Bugs discovered after delivery are fixed under warranty during the support period. After that, they're covered under your maintenance plan.", tags: ["bug", "fix", "issue", "error", "defect"] },
  { id: "s4", category: "Support", question: "What are your support hours?", answer: "We're available 24/7 for critical issues. Standard support requests are handled during business hours with same-day responses.", tags: ["support", "hours", "availability", "24/7"] },
  { id: "s5", category: "Support", question: "Can you maintain software built by another company?", answer: "Yes. We regularly take over and maintain existing applications built by other teams. We start with a code audit and then transition into ongoing support.", tags: ["maintain", "existing", "takeover", "legacy", "other"] },
  { id: "s6", category: "Support", question: "Do you provide training?", answer: "Yes. We provide training for all delivered solutions — including admin training, user training, and documentation. We make sure your team is fully equipped.", tags: ["training", "learn", "teach", "documentation"] },
  { id: "s7", category: "Support", question: "What happens if something breaks in production?", answer: "Our support team responds to critical production issues within 1–2 hours. We have incident response procedures to minimise downtime and resolve issues quickly.", tags: ["production", "break", "down", "incident", "emergency"] },
  { id: "s8", category: "Support", question: "Do you monitor applications after deployment?", answer: "Yes. We offer monitoring services including uptime tracking, error alerting, performance metrics, and automated health checks.", tags: ["monitor", "uptime", "alert", "performance"] },

  // ─── HOSTING & CLOUD ───
  { id: "h1", category: "Hosting", question: "Do you provide hosting?", answer: "Yes. We deploy applications on modern cloud platforms like Vercel, Cloudflare, AWS, or your preferred provider. We handle the complete setup.", tags: ["hosting", "cloud", "server", "deploy"] },
  { id: "h2", category: "Hosting", question: "Which cloud providers do you use?", answer: "We work with Vercel, Cloudflare, AWS, Azure, and Google Cloud. We recommend the best fit based on your project's needs, budget, and compliance requirements.", tags: ["cloud", "aws", "azure", "gcp", "vercel"] },
  { id: "h3", category: "Hosting", question: "Can you migrate my existing application to the cloud?", answer: "Yes. We handle cloud migrations including infrastructure assessment, data migration, testing, and zero-downtime cutover.", tags: ["migrate", "cloud", "migration", "move"] },
  { id: "h4", category: "Hosting", question: "Do you set up CI/CD pipelines?", answer: "Yes. We implement automated CI/CD pipelines using GitHub Actions and other tools so your team can ship updates confidently and frequently.", tags: ["cicd", "pipeline", "deployment", "automation", "github"] },
  { id: "h5", category: "Hosting", question: "How do you handle backups?", answer: "We configure automated daily backups with point-in-time recovery. Backup strategies are tailored to your data criticality and compliance needs.", tags: ["backup", "recovery", "data", "disaster"] },

  // ─── HARDWARE ───
  { id: "hw1", category: "Hardware", question: "What hardware brands do you sell?", answer: "We source from all major enterprise brands and can procure any specific hardware you need. We provide competitive pricing through authorised channels.", tags: ["hardware", "brand", "vendor", "manufacturer"] },
  { id: "hw2", category: "Hardware", question: "Do you offer hardware installation?", answer: "Yes. We provide end-to-end hardware services including procurement, configuration, installation, and desk-ready deployment.", tags: ["hardware", "install", "setup", "configuration"] },
  { id: "hw3", category: "Hardware", question: "Do you supply servers?", answer: "Yes. We supply rack servers, tower servers, and NAS storage systems. We also handle server room design, rack installation, and UPS setup.", tags: ["server", "hardware", "rack", "storage"] },
  { id: "hw4", category: "Hardware", question: "Can you set up CCTV?", answer: "Yes. We design and install IP-based CCTV surveillance systems with remote monitoring, motion detection, and NVR storage.", tags: ["cctv", "surveillance", "camera", "security"] },
  { id: "hw5", category: "Hardware", question: "Do you supply biometric systems?", answer: "Yes. We supply and configure biometric attendance and access control systems including fingerprint, facial recognition, and RFID solutions.", tags: ["biometric", "attendance", "fingerprint", "access"] },
  { id: "hw6", category: "Hardware", question: "Do you set up networking?", answer: "Yes. We handle complete network infrastructure including routers, switches, structured cabling, Wi-Fi, and firewall configuration.", tags: ["network", "router", "switch", "wifi", "cable"] },
  { id: "hw7", category: "Hardware", question: "Do you offer hardware warranties?", answer: "Yes. All hardware comes with standard manufacturer warranties. We also offer extended warranty and AMC options for ongoing hardware support.", tags: ["warranty", "hardware", "guarantee", "protection"] },
  { id: "hw8", category: "Hardware", question: "Can you help with bulk hardware procurement?", answer: "Yes. We handle bulk procurement for large-scale deployments including enterprise negotiations, logistics, and coordinated deployment.", tags: ["bulk", "procurement", "volume", "large", "enterprise"] },
  { id: "hw9", category: "Hardware", question: "Do you provide UPS solutions?", answer: "Yes. We supply and install UPS systems for servers, workstations, and critical infrastructure. We help size the UPS correctly for your load.", tags: ["ups", "power", "battery", "backup"] },

  // ─── NETWORKING & SECURITY ───
  { id: "n1", category: "Networking", question: "Do you set up office networks?", answer: "Yes. We design and deploy complete office network infrastructure — structured cabling, switches, routers, Wi-Fi, and network security.", tags: ["network", "office", "setup", "cabling", "lan"] },
  { id: "n2", category: "Networking", question: "Can you set up a VPN?", answer: "Yes. We configure secure VPN solutions for remote access, site-to-site connectivity, and encrypted communication.", tags: ["vpn", "remote", "access", "secure"] },
  { id: "n3", category: "Networking", question: "Do you offer firewall management?", answer: "Yes. We configure and manage firewalls, intrusion detection systems, and network security appliances.", tags: ["firewall", "security", "protection", "intrusion"] },
  { id: "n4", category: "Networking", question: "Do you conduct security audits?", answer: "Yes. We perform network security audits, vulnerability assessments, and provide remediation recommendations.", tags: ["security", "audit", "vulnerability", "assessment"] },

  // ─── DEVELOPMENT ───
  { id: "d1", category: "Development", question: "Do you build e-commerce websites?", answer: "Yes. We build custom e-commerce platforms with product management, payment integration, inventory tracking, and customer portals.", tags: ["ecommerce", "shop", "store", "online", "sell"] },
  { id: "d2", category: "Development", question: "Do you build mobile apps?", answer: "Yes. We build cross-platform mobile apps for iOS and Android using Flutter, delivering native performance from a single codebase.", tags: ["mobile", "app", "ios", "android", "flutter"] },
  { id: "d3", category: "Development", question: "Can you build an ERP system?", answer: "Yes. We build custom ERP systems tailored to your specific business processes — including modules for inventory, HR, finance, production, and more.", tags: ["erp", "enterprise", "custom", "modules"] },
  { id: "d4", category: "Development", question: "Can you build a CRM?", answer: "Yes. We build custom CRM systems for sales pipeline management, customer tracking, communication logging, and analytics.", tags: ["crm", "customer", "sales", "pipeline"] },
  { id: "d5", category: "Development", question: "Do you build APIs?", answer: "Yes. We design and build RESTful and GraphQL APIs that are secure, well-documented, and scalable.", tags: ["api", "integration", "rest", "backend"] },
  { id: "d6", category: "Development", question: "Can you redesign my existing website?", answer: "Yes. We frequently modernise existing websites — improving design, performance, and SEO while preserving your content and rankings.", tags: ["redesign", "modernise", "existing", "update", "refresh"] },
  { id: "d7", category: "Development", question: "Do you build SaaS products?", answer: "Yes. We've helped startups and businesses build multi-tenant SaaS platforms from MVP to scale.", tags: ["saas", "product", "platform", "startup", "multi-tenant"] },
  { id: "d8", category: "Development", question: "Can you integrate third-party services?", answer: "Yes. We integrate payment gateways, CRMs, ERPs, email services, analytics, and any third-party API your project requires.", tags: ["integrate", "third-party", "api", "payment", "gateway"] },
  { id: "d9", category: "Development", question: "Do you build dashboards?", answer: "Yes. We build custom analytics dashboards with real-time data, charts, reports, and role-based access control.", tags: ["dashboard", "analytics", "report", "chart", "data"] },
  { id: "d10", category: "Development", question: "Can you build a booking system?", answer: "Yes. We build appointment and booking systems with calendar integration, automated reminders, and payment processing.", tags: ["booking", "appointment", "calendar", "schedule"] },
  { id: "d11", category: "Development", question: "Do you build inventory management systems?", answer: "Yes. We build inventory management solutions with barcode scanning, stock alerts, multi-warehouse support, and reporting.", tags: ["inventory", "stock", "warehouse", "management"] },
  { id: "d12", category: "Development", question: "Can you build a patient portal?", answer: "Yes. We build secure healthcare portals for appointments, medical records, lab results, and doctor-patient communication.", tags: ["patient", "portal", "healthcare", "medical", "hospital"] },
  { id: "d13", category: "Development", question: "Do you use WordPress?", answer: "We specialise in custom-built solutions using React and Next.js rather than WordPress. This gives better performance, security, and scalability. However, we can work with WordPress if it's specifically required.", tags: ["wordpress", "cms", "template", "theme"] },
  { id: "d14", category: "Development", question: "Do you work with legacy systems?", answer: "Yes. We modernise legacy applications and help migrate them to modern tech stacks. We also build integration layers to connect legacy systems with new applications.", tags: ["legacy", "old", "modernise", "migrate", "outdated"] },

  // ─── AI & AUTOMATION ───
  { id: "a1", category: "Automation", question: "Can you automate my business workflows?", answer: "Yes. We automate repetitive workflows using tools like n8n, Python, and custom integrations — saving time and reducing errors.", tags: ["automate", "workflow", "process", "repetitive"] },
  { id: "a2", category: "Automation", question: "Can you build a chatbot?", answer: "Yes. We build intelligent chatbots for customer support, lead generation, and internal use — powered by AI or rule-based logic.", tags: ["chatbot", "bot", "assistant", "conversational"] },
  { id: "a3", category: "Automation", question: "Do you offer AI solutions?", answer: "Yes. We build AI-powered solutions including document processing, data analysis, predictive models, chatbots, and intelligent automation.", tags: ["ai", "artificial", "intelligence", "machine", "learning"] },
  { id: "a4", category: "Automation", question: "Can you automate document processing?", answer: "Yes. We build solutions that automatically extract, classify, and process information from documents — invoices, forms, contracts, and more.", tags: ["document", "processing", "ocr", "extract", "invoice"] },
  { id: "a5", category: "Automation", question: "Can you integrate AI into my existing system?", answer: "Yes. We add AI capabilities to existing applications — such as intelligent search, recommendations, natural language processing, and predictive analytics.", tags: ["ai", "integrate", "existing", "add", "enhance"] },

  // ─── SCALABILITY & PERFORMANCE ───
  { id: "sc1", category: "Scalability", question: "Can your solutions handle high traffic?", answer: "Yes. We build for scalability using cloud infrastructure, CDNs, caching, and load balancing. Our architectures are designed to handle traffic spikes gracefully.", tags: ["scale", "traffic", "performance", "load", "users"] },
  { id: "sc2", category: "Scalability", question: "How do you ensure application performance?", answer: "We optimise at every level — database queries, server response times, frontend rendering, image optimisation, and caching strategies.", tags: ["performance", "speed", "optimise", "fast", "slow"] },
  { id: "sc3", category: "Scalability", question: "Can you help with database optimisation?", answer: "Yes. We optimise database schemas, queries, indexing, and caching to ensure fast response times even with large datasets.", tags: ["database", "optimise", "query", "slow", "performance"] },

  // ─── SECURITY ───
  { id: "sec1", category: "Security", question: "How do you handle application security?", answer: "We follow security best practices including encryption, authentication, authorisation, input validation, OWASP guidelines, and regular security audits.", tags: ["security", "safe", "secure", "protection", "hack"] },
  { id: "sec2", category: "Security", question: "Do you handle data privacy compliance?", answer: "Yes. We build applications with data privacy in mind, including GDPR-awareness, data encryption, consent management, and secure storage.", tags: ["privacy", "gdpr", "compliance", "data", "protection"] },
  { id: "sec3", category: "Security", question: "Do you conduct penetration testing?", answer: "We can arrange professional penetration testing as part of our security audit services, or work with your preferred security firm.", tags: ["penetration", "testing", "security", "vulnerability"] },

  // ─── COMPANY ───
  { id: "c1", category: "Company", question: "Where is SIMPLEIN Solutions located?", answer: "SIMPLEIN Solutions is based in India and serves clients globally. We work with businesses worldwide through efficient remote collaboration.", tags: ["location", "where", "office", "address", "based"] },
  { id: "c2", category: "Company", question: "How many people work at SIMPLEIN?", answer: "We maintain a focused, expert team that allows us to deliver personalised attention to every project. We scale teams dynamically based on project requirements.", tags: ["team", "size", "people", "employees", "staff"] },
  { id: "c3", category: "Company", question: "Do you work with international clients?", answer: "Yes. We work with clients worldwide. Our team is experienced in cross-timezone collaboration, regular video updates, and structured project management.", tags: ["international", "global", "overseas", "foreign", "worldwide"] },
  { id: "c4", category: "Company", question: "What industries do you serve?", answer: "We serve Healthcare, Education, Retail, Manufacturing, Finance, Real Estate, Logistics, Hospitality, Government, Startups, SMEs, and Enterprises.", tags: ["industry", "sector", "vertical", "serve", "work"] },
  { id: "c5", category: "Company", question: "Do you sign NDAs?", answer: "Yes. We're happy to sign NDAs before any technical discussion. Confidentiality and data security are fundamental to how we operate.", tags: ["nda", "confidential", "secret", "privacy", "agreement"] },
  { id: "c6", category: "Company", question: "Can I see your portfolio?", answer: "We'd be happy to share relevant case studies and project references during our consultation. Some projects are under NDA, but we can discuss approaches and outcomes.", tags: ["portfolio", "examples", "projects", "case", "work"] },
  { id: "c7", category: "Company", question: "What makes SIMPLEIN different?", answer: "We combine end-to-end capabilities (hardware + software + cloud), modern technology, dedicated project management, and genuine long-term partnership. We're not just a vendor.", tags: ["different", "unique", "why", "special", "advantage"] },
  { id: "c8", category: "Company", question: "Are you hiring?", answer: "We're always open to connecting with talented professionals. Please reach out via email with your resume and we'll get back to you.", tags: ["hiring", "career", "job", "work", "join", "recruit"] },
  { id: "c9", category: "Company", question: "Do you offer internships?", answer: "Yes, we occasionally offer internship opportunities for motivated individuals. Please reach out via email with your interest areas and availability.", tags: ["internship", "intern", "student", "learn", "opportunity"] },

  // ─── PROCESS & METHODOLOGY ───
  { id: "pr1", category: "Process", question: "What development methodology do you use?", answer: "We use Agile methodology with 1–2 week sprints, regular demos, and continuous client feedback. This ensures transparency and alignment throughout.", tags: ["agile", "methodology", "scrum", "sprint", "process"] },
  { id: "pr2", category: "Process", question: "How do you manage projects?", answer: "Each project has a dedicated project manager who handles communication, timelines, and deliverables. We use tools like GitHub, Slack, and video calls for transparency.", tags: ["project", "management", "communication", "manager"] },
  { id: "pr3", category: "Process", question: "Will I get regular updates?", answer: "Yes. We provide regular progress updates, typically weekly or bi-weekly, including demos of new features and upcoming milestone reviews.", tags: ["updates", "progress", "communication", "regular", "demo"] },
  { id: "pr4", category: "Process", question: "Can I be involved in the development process?", answer: "Absolutely. We encourage active client involvement through sprint reviews, feedback sessions, and collaborative tools. The best projects are built together.", tags: ["involved", "participate", "collaborate", "feedback"] },
  { id: "pr5", category: "Process", question: "Do you provide documentation?", answer: "Yes. Every project includes comprehensive documentation — technical docs, user guides, API references, and deployment procedures.", tags: ["documentation", "docs", "manual", "guide"] },
  { id: "pr6", category: "Process", question: "Do you use version control?", answer: "Yes. All code is managed with Git via GitHub, with proper branching strategies, code reviews, and automated testing.", tags: ["git", "github", "version", "control", "code"] },

  // ─── DEPLOYMENT ───
  { id: "dep1", category: "Deployment", question: "How do you handle deployment?", answer: "We set up automated deployment pipelines so updates can be shipped safely and frequently. We use staging environments for testing before production.", tags: ["deployment", "release", "launch", "production", "live"] },
  { id: "dep2", category: "Deployment", question: "Do you offer staging environments?", answer: "Yes. We always set up staging environments where you can review and test changes before they go live.", tags: ["staging", "testing", "environment", "preview"] },
  { id: "dep3", category: "Deployment", question: "Can you deploy on-premise?", answer: "Yes. While we recommend cloud deployment for most projects, we can deploy applications on your own servers if required.", tags: ["on-premise", "local", "server", "self-hosted"] },

  // ─── INTEGRATION ───
  { id: "int1", category: "Integration", question: "Can you integrate with my existing systems?", answer: "Yes. We specialise in system integration — connecting new applications with existing ERPs, CRMs, accounting systems, and third-party services.", tags: ["integrate", "existing", "connect", "system", "api"] },
  { id: "int2", category: "Integration", question: "Do you integrate payment gateways?", answer: "Yes. We integrate payment gateways like Razorpay, Stripe, PayPal, and others depending on your market and requirements.", tags: ["payment", "gateway", "razorpay", "stripe", "paypal"] },
  { id: "int3", category: "Integration", question: "Can you connect with accounting software?", answer: "Yes. We integrate with accounting platforms like Tally, QuickBooks, and Zoho Books for automated financial data flow.", tags: ["accounting", "tally", "quickbooks", "zoho", "finance"] },

  // ─── TRAINING & ONBOARDING ───
  { id: "tr1", category: "Training", question: "Do you train our team to use the software?", answer: "Yes. We provide hands-on training sessions, video tutorials, and documentation to ensure your team is fully comfortable with the delivered solution.", tags: ["training", "onboarding", "learn", "use", "teach"] },
  { id: "tr2", category: "Training", question: "Do you provide user documentation?", answer: "Yes. Every project includes user-facing documentation, admin guides, and where relevant, video walkthroughs.", tags: ["documentation", "guide", "manual", "user", "help"] },

  // ─── DIGITAL MARKETING ───
  { id: "dm1", category: "Marketing", question: "Do you offer SEO services?", answer: "Yes. We provide search engine optimisation including technical SEO, content strategy, keyword research, and performance tracking.", tags: ["seo", "search", "google", "ranking", "visibility"] },
  { id: "dm2", category: "Marketing", question: "Do you manage social media?", answer: "Yes. We offer social media management including content creation, scheduling, engagement, and analytics across major platforms.", tags: ["social", "media", "instagram", "facebook", "linkedin"] },
  { id: "dm3", category: "Marketing", question: "Can you run Google Ads?", answer: "Yes. We set up and manage Google Ads campaigns including search, display, and remarketing — optimised for your target audience and ROI.", tags: ["google", "ads", "advertising", "ppc", "campaign"] },
  { id: "dm4", category: "Marketing", question: "Do you help with branding?", answer: "Yes. We offer brand strategy services including visual identity, messaging, positioning, and digital brand presence.", tags: ["branding", "brand", "identity", "logo", "design"] },

  // ─── CONSULTATION ───
  { id: "con1", category: "Consultation", question: "How do I get started?", answer: "Simply reach out via WhatsApp, email, or phone. We'll schedule a free 30-minute consultation to understand your needs, and follow up with a tailored proposal.", tags: ["start", "begin", "how", "first", "step"] },
  { id: "con2", category: "Consultation", question: "What happens during the consultation?", answer: "We discuss your business goals, current challenges, technical requirements, and timeline. We then prepare a detailed proposal with scope, technology recommendations, and estimated timeline.", tags: ["consultation", "meeting", "discuss", "what", "expect"] },
  { id: "con3", category: "Consultation", question: "How long does it take to get a proposal?", answer: "We typically deliver a detailed proposal within 3–5 business days after the initial consultation.", tags: ["proposal", "timeline", "how long", "estimate", "quote"] },
  { id: "con4", category: "Consultation", question: "Can I schedule a call?", answer: "Yes! You can call us directly at +91 984 8334 984, send a WhatsApp message, or email us at info@simpleinsolutions.com. We'll set up a convenient time.", tags: ["call", "schedule", "meeting", "phone", "appointment"] },

  // ─── TECHNOLOGIES ───
  { id: "tech1", category: "Technologies", question: "Why do you use React?", answer: "React offers component-based architecture, excellent performance, a massive ecosystem, and strong community support. It's the most popular frontend framework globally and ensures long-term maintainability.", tags: ["react", "why", "frontend", "framework"] },
  { id: "tech2", category: "Technologies", question: "Why do you use Next.js?", answer: "Next.js provides server-side rendering, static generation, excellent SEO, API routes, and optimised performance out of the box. It's the gold standard for production React applications.", tags: ["nextjs", "next", "why", "ssr", "framework"] },
  { id: "tech3", category: "Technologies", question: "Why Flutter instead of React Native?", answer: "Flutter delivers native-quality performance on both platforms, has a rich widget library, and allows for faster development with a single codebase. The developer experience and design flexibility are excellent.", tags: ["flutter", "react native", "why", "mobile", "cross-platform"] },
  { id: "tech4", category: "Technologies", question: "Do you use TypeScript?", answer: "Yes. TypeScript is our default for all web projects. It catches errors at compile time, improves code quality, and makes large codebases much easier to maintain.", tags: ["typescript", "type", "javascript", "language"] },
  { id: "tech5", category: "Technologies", question: "Why PostgreSQL?", answer: "PostgreSQL is a powerful, open-source database with excellent reliability, advanced features, JSON support, and strong community backing. It handles everything from small apps to enterprise workloads.", tags: ["postgresql", "postgres", "database", "why", "sql"] },
  { id: "tech6", category: "Technologies", question: "Do you work with Python?", answer: "Yes. We use Python extensively for backend development, automation, AI/ML projects, data processing, and API development using FastAPI.", tags: ["python", "backend", "automation", "ai", "fastapi"] },
  { id: "tech7", category: "Technologies", question: "Do you use Docker?", answer: "Yes. We use Docker for containerisation, ensuring consistent environments across development, staging, and production.", tags: ["docker", "container", "devops", "deployment"] },

  // ─── MISCELLANEOUS ───
  { id: "m1", category: "General", question: "Do you offer white-label solutions?", answer: "Yes. We can build solutions that are fully white-labelled with your brand, allowing you to resell or present them as your own product.", tags: ["white-label", "resell", "brand", "label"] },
  { id: "m2", category: "General", question: "Can you build an MVP?", answer: "Yes. We specialise in helping startups build MVPs — focused, lean products that validate your idea and attract early users or investors.", tags: ["mvp", "minimum", "viable", "startup", "prototype"] },
  { id: "m3", category: "General", question: "Do you offer dedicated developers?", answer: "Yes. We offer dedicated developer engagement for clients who need consistent, long-term development capacity integrated with their team.", tags: ["dedicated", "developer", "hire", "team", "outsource"] },
  { id: "m4", category: "General", question: "Can you help with digital transformation?", answer: "Yes. We help businesses transition from manual and legacy processes to modern, digital-first operations — covering strategy, implementation, and training.", tags: ["digital", "transformation", "modernise", "strategy"] },
  { id: "m5", category: "General", question: "Do you build Progressive Web Apps?", answer: "Yes. PWAs are a great option for businesses wanting app-like experiences without requiring app store distribution. They work offline and are installable.", tags: ["pwa", "progressive", "web", "app", "offline"] },
  { id: "m6", category: "General", question: "Can you build a real-time application?", answer: "Yes. We build real-time features using WebSockets and server-sent events — including live chat, notifications, dashboards, and collaboration tools.", tags: ["realtime", "real-time", "live", "websocket", "chat"] },
  { id: "m7", category: "General", question: "Do you handle data migration?", answer: "Yes. We plan and execute data migrations carefully — including data mapping, validation, transformation, and verification to ensure zero data loss.", tags: ["migration", "data", "move", "transfer", "import"] },
  { id: "m8", category: "General", question: "Can I own the source code?", answer: "Yes. Upon project completion and final payment, you receive full ownership of all source code, documentation, and assets.", tags: ["source", "code", "ownership", "rights", "ip"] },
  { id: "m9", category: "General", question: "Do you use open-source technologies?", answer: "Yes. Our entire stack is built on open-source technologies — React, Next.js, Node.js, Python, PostgreSQL, Flutter. This avoids vendor lock-in and reduces licensing costs.", tags: ["open-source", "free", "license", "vendor"] },
  { id: "m10", category: "General", question: "What is your refund policy?", answer: "We work on milestone-based billing, so you only pay for completed work. If a project needs to be cancelled, you retain all work completed up to that point.", tags: ["refund", "cancel", "policy", "money", "back"] },
];
